### ISSUE TITLE
Issue with tags

### ISSUE THREAD

**Issue by lnlyssg** [huyz/brew-for-linux-arm#1]
### `brew doctor` output

```shell
-
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
-
```

### What were you trying to do (and why)?

Install homebrew on an arm machine, I followed the instructions in the README but the install script has changed and now check for tags which are not present as per  https://github.com/Homebrew/install/commit/8eb03394e3f4081c1519fc01bb562faf0c6fbd14

### What happened (include all command output)?

`Failed to query latest Homebrew/brew Git tag.`

### What did you expect to happen?

Homebrew to install

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build  # apt's ruby-build is too out of date
rbenv install 2.6.10
rbenv shell 2.6.10
export HOMEBREW_BREW_GIT_REMOTE=https://github.com/huyz/brew-for-linux-arm
export HOMEBREW_DEVELOPER=1
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | sed '532s/abort/warn/')"
[...]
==> Downloading and installing Homebrew...
Failed to query latest Homebrew/brew Git tag.
```

And with set -x you can see where it fails::
```
++ /usr/bin/git tag --list --sort=-version:refname
+ LATEST_GIT_TAG=
+ [[ -z '' ]]
+ abort 'Failed to query latest Homebrew/brew Git tag.'
+ printf '%s\n' 'Failed to query latest Homebrew/brew Git tag.'
Failed to query latest Homebrew/brew Git tag.
```

**Comment by finch-alt** [comment]
@lnlyssg It's require at least one tag in the repo. You can fork it and put the tag, or just use mine as temporary workaround. https://github.com/sergeycherepanov/linuxbrew-arm

**Comment by sergeycherepanov** [comment]
Hi @lnlyssg,

It's require at least one tag in the repo. You can fork it and put the tag, or just use mine as temporary workaround. https://github.com/sergeycherepanov/linuxbrew-arm

cc @huyz

**Comment by lnlyssg** [comment]
@sergeycherepanov I ended up making my own fork from brew then adding the extras from this repo to it back in April - https://github.com/lnlyssg/brew

**Comment by huyz** [comment]
Oh I missed this issue somehow. I'll take a look at it
